### ISSUE TITLE
Yeni versiyalarda uyğunsuzluq

### ISSUE THREAD

**Issue by alievinfo** [thr3w/Epoint-Opencart-3.0#1]
Salam,

Göndərilən faylları yükləyəndən sonra aktiv etmək üçün görünmür. Problemi həll etmək üçün dəstək olmağınızı xahiş edirəm.

![image](https://github.com/thr3w/Epoint-Opencart-3.0/assets/4084014/b475a3f1-d610-45e6-a757-159dc97e0662)

**Comment by thr3w** [comment]
Dear alievinfo,

Thank you for your feedback. The issue has been resolved, and we have released version 2.1. You now have the option to update to version 4.0.1 or remain on version 3.0.3.8. For any future issues, please open a new ticket.

Best regards, 
Thre3w
