### ISSUE TITLE
3.0.3.9 versiyası

### ISSUE THREAD

**Issue by alievinfo** [thr3w/Epoint-Opencart-3.0#2]
Salam,

3.0.3.9 versiyasında da qeyd edilən problem yaşanır. Faylları qeyd edilən qovluqlara atmışıq. admin və catalog

**Comment by alievinfo** [comment]
Git-dən faylı yükləyib .ocmod.zip edərək yükləməyi yoxladıq, modul yükləndi amm ayenə extensions-da göstərmədi.

**Comment by alievinfo** [comment]
PHP-nin versiyasi:: PHP Version 8.1.2

**Comment by thr3w** [comment]
Dear alievinfo,

Thank you for your feedback. The issue has been resolved, and we have released version 2.1. You now have the option to update to version 4.0.1 or remain on version 3.0.3.8. For any future issues, please open a new ticket.

Best regards, 
Thre3w
