### ISSUE TITLE
Version 3.0.3.8

### ISSUE THREAD

**Issue by alievinfo** [thr3w/Epoint-Opencart-3.0#3]
Test üçün Version 3.0.3.8 versiyasını yüklədik.
PAyments hissəsində 52 extension var, epointdən başqa.

![image](https://github.com/thr3w/Epoint-Opencart-3.0/assets/4084014/feff33bb-8396-46a2-aa64-eadd9c56fb7c)

**Comment by thr3w** [comment]
Dear alievinfo,

Thank you for your feedback. We've successfully resolved the issue, and we're pleased to announce the release of version 2.1. Now, you have the option to update to version 4.0.1 or remain on version 3.0.3.8.
