### ISSUE TITLE
API Linklər

### ISSUE THREAD

**Issue by alievinfo** [thr3w/Epoint-Opencart-3.0#5]
opencart üçünsistemdə qeyd ediləcək linklər necə yazılmalıdır? 
Success page, Error page və Result page?

**Comment by thr3w** [comment]
Dear alievinfo,

From your question, it appears that your inquiry is not directly related to the development of this module but rather to the Epoint registration form. 
Epoint Support may be able to assist you.

Thank you.

Best regards,
Thr3w

> opencart üçünsistemdə qeyd ediləcək linklər necə yazılmalıdır? Success page, Error page və Result page?
